-- Supabase Schema for FermaAgent Demo

-- Customers Table
CREATE TABLE IF NOT EXISTS customers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    historical_ltv NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    support_tickets_count INTEGER NOT NULL DEFAULT 0,
    days_since_last_order INTEGER NOT NULL DEFAULT 0,
    loyalty_tier TEXT NOT NULL DEFAULT 'Tier 1'
);

-- Inventory Table
CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    retail_price NUMERIC(10, 2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0
);

-- Deliveries Table
CREATE TABLE IF NOT EXISTS deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'dispatched',
    target_lat NUMERIC(9, 6) NOT NULL,
    target_lon NUMERIC(9, 6) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id TEXT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    amount NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL,
    items JSONB NOT NULL DEFAULT '[]'::jsonb
);

-- Agent Traces Table
CREATE TABLE IF NOT EXISTS agent_traces (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    latency_ms INTEGER NOT NULL,
    trace_log JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_agent_traces_order_id ON agent_traces(order_id);

-- Disable Row Level Security (RLS) for demo/presentation access via publishable key
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE agent_traces DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE deliveries DISABLE ROW LEVEL SECURITY;

-- Alternatively, if RLS is enforced at the project level, allow all operations:
-- DROP POLICY IF EXISTS "Allow all on customers" ON customers;
-- CREATE POLICY "Allow all on customers" ON customers FOR ALL TO public USING (true) WITH CHECK (true);
-- DROP POLICY IF EXISTS "Allow all on orders" ON orders;
-- CREATE POLICY "Allow all on orders" ON orders FOR ALL TO public USING (true) WITH CHECK (true);
-- DROP POLICY IF EXISTS "Allow all on agent_traces" ON agent_traces;
-- CREATE POLICY "Allow all on agent_traces" ON agent_traces FOR ALL TO public USING (true) WITH CHECK (true);

