-- Supabase Schema for FermaAgent Demo

-- Customers Table
CREATE TABLE IF NOT EXISTS customers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    historical_ltv NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    support_tickets_count INTEGER NOT NULL DEFAULT 0,
    days_since_last_order INTEGER NOT NULL DEFAULT 0,
    loyalty_tier TEXT NOT NULL DEFAULT 'Tier 1'
);

-- Inventory Table
CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    retail_price NUMERIC(10, 2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0
);

-- Deliveries Table
CREATE TABLE IF NOT EXISTS deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'dispatched',
    target_lat NUMERIC(9, 6) NOT NULL,
    target_lon NUMERIC(9, 6) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id TEXT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    amount NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL,
    items JSONB NOT NULL DEFAULT '[]'::jsonb
);

-- Agent Traces Table
CREATE TABLE IF NOT EXISTS agent_traces (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
    agent_flow TEXT NOT NULL DEFAULT 'b2c',
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    latency_ms INTEGER NOT NULL,
    trace_log JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_agent_traces_order_id ON agent_traces(order_id);

-- Enable Row Level Security (RLS)
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_traces ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE deliveries ENABLE ROW LEVEL SECURITY;

-- Allow full access to authenticated/service_role keys
CREATE POLICY "Allow service_role full access to customers" ON customers FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow service_role full access to orders" ON orders FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow service_role full access to agent_traces" ON agent_traces FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow service_role full access to inventory" ON inventory FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow service_role full access to deliveries" ON deliveries FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Allow anon role read/write access for the demo (since the Python SDK defaults to anon if not configured)
CREATE POLICY "Allow anon access to customers" ON customers FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon access to orders" ON orders FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon access to agent_traces" ON agent_traces FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon access to inventory" ON inventory FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon access to deliveries" ON deliveries FOR ALL TO anon USING (true) WITH CHECK (true);

