FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir fastapi uvicorn scikit-learn joblib numpy pydantic httpx

COPY . /app

EXPOSE 8001

CMD ["uvicorn", "app.ml.service:ml_app", "--host", "0.0.0.0", "--port", "8001"]
